{
    "input_extension_images": "jpg",
    "output_extension_images": "png",
    "tile_size": 150,
    "step_size": 50,
    "input_dir_images": "/home/kalfasyan/data/solarpanelsv2/train",
    "input_dir_annotations": "/home/kalfasyan/data/solarpanelsv2/train",
    "input_format_annotations": "coco",
    "output_dir_images": "output/images",
    "output_dir_annotations": "output/annotations",
    "output_format_annotations": "yolo",
    "annotation_mapping": {
        "kernel": 0,
        "person": 1,
        "bottle": 2,
        "empty": 3,
        "trafficlight": 4,
        "speedlimit": 5,
        "crosswalk": 6,
        "stop": 7
    },
    "validate_settings": false,
    "log": false,
    "log_folder": "logs",
    "num_workers": -1,
    "clear_duplicates": false,
}
